travis:
  secure:
    BINSTAR_TOKEN: QQcM81p5725uSOVvrm1O/G+GtSvJHhHbWhaGU38KF011eZoeHLNM9od2jK6lsLwIAh524LDBHBrvB+FivZzDEkHTcV3aDMa9ygfxX1IA77Og3+qmKu+b9VDmCkPLcNkuVsG5fKXwHR1PJX36OcLtGvGTUy3lfAFswXAN3+G2foEWMi22nr3N/NX4Q5vje9mySRetfsGEUB5k4HKLb6ThND9uuItVQTpghPn8xfFV0f8bsPLjGqknMHamqCzjLpQJK4Wwola2Yi2M2ZgttReii2DsMNjtDfDeXEv+BsHdYwSqCtbDtmrXWexquhOPorSACh5lKQwBXdtciucV3S0SseasttsH9P9XhPUBFGL9pFJHzRBCvDuaKq6ouaPUUko3bSHm1YtFaNRQjYpwx06681zTIUci13+1g/DgmA4tu0xDzLNpGHRHBaXIEQ8cNadv5H+qWsu7EZxV6nFbdNVvJBJBCNxt7RSZbXloUG8m+UfoY9lnKCsDCwl2C32i/2a7sE/fyszuVmrXguPwZwT3PFQtO7n8Es5MLeOJWRdD7//u9QKrhSbK7Q2qz1+uKfPij8BsnteBbu9s6ASJMcBUCddZ4Ynu6DihBZdvQU/qU8vjr0xo73IEqBDMV35uyi0cAwLwIXQd+Ewqki/eMiZ2jYsQv1SLh3cVNGToy2KO6s8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
