travis:
  secure:
    BINSTAR_TOKEN: LKVoIIUEFrZKwbfCxYFXKt3WzjXR35e7XjKxU+o8B7tOncTJV603gQq9WVl+1QXBN3f44rQWh/sXDMfBJzhSiqIPC8p8+PoVgDD1AMX8R3lGXhBtrjvGxd7+HNONj+oadgtxzhe+oIwXO/hVP+2NrHfhIIdhSYJ3nr9et9aL3Kj92q5g+mJ3g2vSHDYNa9pLufbEj8VYbYD4PtvXww9MuGL7TbCr1RTNLe3IhWKTL2453PSATlGExhckOzxH/3zaJQR10/0MibGDPKxSe7Ax8EMVWgjANuIoFj9iZkzwnY1m4i2G4GXK4pJ05kUzurHJo4HJHQojy5ocWUTWYIuyG+2PJobkXBkVk6Lc1TPVc/RdSpjwItnKu6h54XaVJdyS99MXKkhCqn23i2A8E7bikA65jW9XmJY9xgP1SRyVAzpOt4Nkdr9ZmKiO5y19SfblQTHf9EF1U7EdjB1g/CgYb22Ywof42wsyDbvwTg6uaoRaK5ryQtEV/KyQhy4X41AqB3ZuNlzYLd3TA8ER88BSYcnvkq2L5Yp/0Q7Pf9nPmZOS3rgHU4dq4+lNnR1mn5vQHqEYGN5mReJ7lyZVxS/uNBRSwvjSGl9xSceOEYCEO/ZL8VsiIaRL8mCvpB2wuLDiPssO/mCnA5wAZNnT7RhwcDX8mwnkXwSa+C0IcE5XAdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
